spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/shopifake}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/shopifake/protocol/openid-connect/certs}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}
  realm: shopifake
  admin:
    username: admin
    password: pwd
    client-id: admin-cli

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.shopifake.auth: DEBUG
    org.springframework.security: DEBUG
