apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: shopifake-prod
data:
  NODE_ENV: "production"
  PORT: "5173"
  VITE_API_BASE_URL: "http://main-api.shopifake-prod.svc.cluster.local:80"
  VITE_IMAGE_SERVICE_URL: "http://image-service.shopifake-prod.svc.cluster.local:80"
  VITE_AUTH_SERVICE_URL: "http://auth-service.shopifake-prod.svc.cluster.local:80"
  VITE_CHATBOT_SERVICE_URL: "http://chatbot-service.shopifake-prod.svc.cluster.local:80"

