apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: main-strip-prefix
  namespace: shopifake-prod
spec:
  stripPrefix:
    prefixes:
      - /api/main
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-strip-prefix
  namespace: shopifake-prod
spec:
  stripPrefix:
    prefixes:
      - /api/auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: image-strip-prefix
  namespace: shopifake-prod
spec:
  stripPrefix:
    prefixes:
      - /api/image
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chatbot-strip-prefix
  namespace: shopifake-prod
spec:
  stripPrefix:
    prefixes:
      - /api/chatbot
