apiVersion: v1
kind: Namespace
metadata:
  name: shopifake-prod
  labels:
    app: shopifake
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: shopifake-staging
  labels:
    app: shopifake
    environment: staging

