apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: shopifake-prod
data:

  # Keycloak Configuration
  KEYCLOAK_URL: "http://keycloak.shopifake-prod.svc.cluster.local:8080"
  KEYCLOAK_REALM: "shopifake"
  KEYCLOAK_CLIENT_ID: "shopifake"

  # OAuth2 Resource Server
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://keycloak.shopifake.duckdns.org/realms/shopifake"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://keycloak.shopifake.duckdns.org/realms/shopifake/protocol/openid-connect/certs"

  # Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"

