apiVersion: v1
kind: ConfigMap
metadata:
  name: main-api-config
  namespace: shopifake-prod
data:
  SERVER_PORT: "8080"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/main_api"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "pwd"

  WEBHOOK_CHATBOT_URL: "http://chatbot-service.shopifake-prod.svc.cluster.local:80"
  IMAGE_SERVICE_URL: "http://image-service.shopifake-prod.svc.cluster.local:80"

