apiVersion: v1
kind: ConfigMap
metadata:
  name: main-api-config
  namespace: shopifake-prod
data:
  # Application
  SPRING_APPLICATION_NAME: "main-api"
  SERVER_PORT: "8080"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/main_api"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "pwd"

  # JPA/Hibernate
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

  # Flyway
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

  # Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"

