apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: chatbot-test
data:
  OPENAI_MODEL: "gpt-5-nano"
  OPENAI_EMBED_MODEL: "text-embedding-3-small"
  QDRANT_URL: "http://qdrant-service:6333"
  QDRANT_COLLECTION: "products"
