name: Build & Deploy Image Service

on:
  push:
    branches: [ develop, main, feat/ci-cd ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/image-service

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Can GHCR login?
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin


      - uses: docker/build-push-action@v6

        with:
          context: ./backend/image-service
          file: ./backend/image-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      service-name: 'image-service'
      k8s-manifests-path: 'k8s/image-service'
      namespace: 'shopifake-prod'
      deployments: 'image-service'
    secrets:
      KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

  
